# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d078a3de8250c774f4719e9a51c328c7f93c0b3f06f6d8eadc8581faaf90f9b53aec7b455466a5555eb532bea7bd3ccded1d6ed8f739e1227ba0f1ed5e4cace

test:
  secret_key_base: a7304ab2accfda24158f55d79ecf646569cf0f373dfa49920586aaba783934ee4952a7969c254d295d7131f2bae994a62d76532f67adf9205153940f958c6b72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
